#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2014    Amir Mohammadi <183.amir@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.    See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# get the full path of the file
import os
import sys

if os.path.dirname(sys.argv[0]) != '.':
    if sys.argv[0][0] == '/':
        FULL_PATH = os.path.dirname(sys.argv[0])
    else:
        FULL_PATH = os.getcwd() + '/' + os.path.dirname(sys.argv[0])
else:
    FULL_PATH = os.getcwd()

# argument parser
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-m', "--no-main-window",
                    help='does not display the main window',
                    action="store_true")
parser.add_argument('-v', "--verbose",
                    help='prints more info',
                    action="store_true")
args = parser.parse_args()

# load the settings
from gs_settings import config
if args.verbose:
    config['Global']['verbose'] = 'True'


if __name__ == '__main__':
    from gi.repository import Gtk
    from gs_main_window import MainWindow
    win = MainWindow(FULL_PATH, config)
    win.connect('delete-event', Gtk.main_quit)
    win.set_icon_name('persian-calendar')
    win.show_all()
    if args.no_main_window:
        win.toggle_main_win()
    Gtk.main()
