
.TH "gahshomar" "1" "Last Modified Jan 01, 2015" "" ""
.SH "NAME"
\fBGahshomar\fP \- An elegant two view calendar.

.SH "SYNOPSIS"
.B gahshomar [\fIOPTIONS\fP]

.SH "DESCRIPTION"
\fBGahshomar\fP is a calendar with simplicity in design and elegance in
execution. Gahshomar can:
.IP "  \(bu" 5
View different calendars at the same time

.SH "OPTIONS"
This program accepts the standard GNOME and GTK options.

.TP
.B \-d, \-\-debug
Run Gahshomar in debugging mode.
.br

.SH "LICENSE"
Gahshomar is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

.SH "AUTHORS"
Gahshomar was written by Amir Mohammadi and others.
.br
